platform :ios, '9.0'

target 'mtgx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

  target 'mtgxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mtgx-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'mtgx-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
